# Generated by Django 3.0.8 on 2020-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('species', models.CharField(choices=[('crow', 'Crow'), ('magpie', 'Magpie'), ('pigeon', 'Pigeon'), ('sparrow', 'Sparrow'), ('titmouse', 'Titmouse')], max_length=255)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('black & white', 'Black White'), ('grey', 'Grey'), ('red', 'Red'), ('red & white', 'Red White')], max_length=255)),
                ('body_length', models.PositiveIntegerField()),
                ('wingspan', models.PositiveIntegerField()),
            ],
        ),
    ]
